config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :book_authors
  resources :books
  resources :authors

  get '/authors/:id', :to => 'author#show'

  root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  validates :date_of_birth, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_authors
  has_many :authors, through: :book_authors
  accepts_nested_attributes_for :book_authors
  validates :title, presence: true
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_author, only: %i[ show edit update destroy ]

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def show
    @books = Author.find(params[:id]).books
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path, notice: "Author was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @author.update(author_params)
      redirect_to authors_path, notice: "Author was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_url, notice: "Author was successfully destroyed."
  end

  private
    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:first_name, :last_name, :date_of_birth)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: "Book was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed."
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, author_ids: [])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%=form_with model: @author, url: authors_path do |f|%>
  <p>
    <%= f.label 'First Name:'%><br>
    <%= f.text_field :first_name%>
  </p>
  <p>
    <%= f.label 'Last Name:'%><br>
    <%= f.text_field :last_name%>
  </p>
  <p>
    <%= f.label 'Date of Birth:'%><br>
    <%= f.date_field :date_of_birth, class: 'form-control' %>
  </p>
  <p class="actions">
    <%= f.submit %>
  </p>
<%end%>

app/views/authors/edit.html.erb
<div class="subjects edit"> 
  <h1>Editing Author</h1>

  <%= form_for(@author, :url => author_path(@author), :method=>'patch') do |f| %>
    <%=render(:partial =>'form', :locals => {:f=>f})%>
  <% end %>
</div>

<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style = "text-align:center;">Authors</h1>
<p style = "text-align:center; margin: 20px 1px">
<%= link_to 'Create new Author', new_author_path %>
</p>

<% if @authors.present? %>
  <table style = "margin:auto; border: 1px solid black; cell-padding:9px">
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.first_name%> <%=author.last_name %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %></td>
          <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>No Author found</h3>
<% end %>

<br>

app/views/authors/new.html.erb
<div>
  <h1 style= 'text-align:center'>Create New Author</h1>
  
  <%= form_for(@author, :url => authors_path, :method => 'post') do |f| %>
    <%=render(:partial =>'form', :locals => {:f=>f})%>
  <% end %>
</div>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1 style= 'text-align:center'>Authors and Books they wrote</h1>

<% if @books.present? %>
  <div style= 'margin-top: 10px'>
    <table style = "margin:auto; cell-padding:9px">
      <tbody>
        <% @books.each do |book| %>
          <tr >
            <td><h3>title: </h3></td>
            <td><%= book.title%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <h3>No book found</h3>
<% end %>

<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%=form_with model: @book, url: books_path do |f|%>
  <p>
    <%= f.label 'Title:'%><br>
    <%= f.text_field :title%>

    <%= f.label 'Author:'%><br>
    
    <% Author.all.each do |author|%>
      <%= check_box_tag "book[author_ids][]", author.id, f.object.authors.include?(author), {multiple: true} %>
      <%=author.first_name%>
    <%end%>
  </p>
  <p class="actions">
    <%= f.submit %>
  </p>
<%end%>

app/views/books/edit.html.erb
<div class="subjects edit"> 
  <h1>Editing Book</h1>

  <%= form_for(@book, :url => book_path(@book), :method=>'patch') do |f| %>
    <%=render(:partial =>'form', :locals => {:f=>f})%>
  <% end %>
</div>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style = "text-align:center;">Books</h1>
<p style = "text-align:center; margin: 20px 1px">
<%= link_to 'Create new Book', new_book_path %>
</p>

<% if @books.present? %>
  <table style = "margin:auto; border: 1px solid black; cell-padding:9px">
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title%></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>No book found</h3>
<% end %>

<br>

app/views/books/new.html.erb
<div>
  <h1 style= 'text-align:center'>Create New Book</h1>
  
  <%= form_for(@book, :url => books_path, :method => 'post') do |f| %>
    <%=render(:partial =>'form', :locals => {:f=>f})%>
  <% end %>
</div>

<%= link_to 'Back', books_path %>

app/views/homes/index.html.erb
<h1 style = "text-align:center;">Welcome to The Book Publication</h1>
<p style = "margin: 20px 1px"></p>

<p style = "text-align:center;">
  <%= link_to 'Display Authors', authors_path%>
  <%= link_to 'Display Books', books_path%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookPublicationDefinelabs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>